# ----------------------------------------
# Environment variable WISELIB_PATH needed
# ----------------------------------------

 all: shawn
# all: scw_msb
# all: contiki_msb
# all: contiki_micaz
# all: isense
# all: tinyos-tossim
# all: tinyos-micaz

export APP_SRC=remote_app.cpp
export BIN_OUT=remote_app

include ../Makefile
